### PR TITLE
fix(#229): add if statment to return 404

### LINKED ISSUE #226: Fix CloudFront 500 error on non-existent paths (should return 404)
**Describe the bug**
When requesting a non-existent path /new on vilnacrm.com, CloudFront sometimes returns 500 Internal Server Error, even though the origin (S3) correctly responds with 404 Not Found. The issue appears to come from CloudFront configuration (custom error mapping or a Lambda@Edge override), not from the routing function itself.

**To Reproduce**
1. Go to [https://vilnacrm.com/new](https://vilnacrm.com/new?utm_source=chatgpt.com)
2. Or run:
    curl -I https://vilnacrm.com/new
3. Rsponse may be 500 instead of 404.

**Expected behavior**
Requests to non-existent paths should return 404 Not Found, not 500

Additional context

The CloudFront Function only rewrites URIs and cannot generate a 500.
Likely causes:
- CloudFront Custom Error Pages mapping 404/403 to 500.
- A Lambda@Edge (viewer-response or origin-response) overriding status codes.
The routing function was updated to avoid rewriting unknown single-segment paths (e.g. /new), leaving them as-is so that S3 returns the native 404.

### LINKED ISSUE #229: Fix CloudFront 500 error on non-existent paths (should return 404)
**Describe the bug**
When requesting a non-existent path /new on vilnacrm.com, CloudFront sometimes returns 500 Internal Server Error, even though the origin (S3) correctly responds with 404 Not Found. The issue appears to come from CloudFront configuration (custom error mapping or a Lambda@Edge override), not from the routing function itself.

**To Reproduce**
1. Go to [https://vilnacrm.com/new](https://vilnacrm.com/new?utm_source=chatgpt.com)
2. Or run:
    curl -I https://vilnacrm.com/new
3. Rsponse may be 500 instead of 404.

**Expected behavior**
Requests to non-existent paths should return 404 Not Found, not 500

Additional context

The CloudFront Function only rewrites URIs and cannot generate a 500.
Likely causes:
- CloudFront Custom Error Pages mapping 404/403 to 500.
- A Lambda@Edge (viewer-response or origin-response) overriding status codes.
The routing function was updated to avoid rewriting unknown single-segment paths (e.g. /new), leaving them as-is so that S3 returns the native 404.

### PR DESCRIPTION
**Pull request by bra1n2h**
## Description
Updated the CloudFront routing function so that unknown single-segment paths (e.g. /new) are no longer rewritten to /new/index.html. This allows the origin (S3) to return the correct 404 Not Found instead of CloudFront incorrectly mapping it to a 500 Internal Server Error.

## Related Issue
Fixes #226 

## Motivation and Context
This change ensures that missing resources return the correct HTTP status code (404) instead of 500, which:
- Improves debugging and log accuracy.
- Prevents false alarms in monitoring systems that interpret 500 as an internal server error.
- Provides the expected behavior for end users when navigating to non-existent routes.

## How Has This Been Tested?
Deployed updated CloudFront Function in a staging environment.
Tested with curl -I https://vilnacrm.com/new → received 404 Not Found as expected.
Verified that existing mapped routes (/, /about, /en, /swagger) still resolve correctly.
Confirmed logs no longer contain 500 responses for missing single-segment paths.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING.md**](https://github.com/VilnaCRM-Org/frontend-ssr-template/blob/main/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] New components have been added to Storybook.
- [x] You have only one commit (if not, squash them into one commit).

## Summary by CodeRabbit

* **New Features**
  * Faster exact-route handling for matched URLs.
  * URIs that look like static assets (file extensions) are passed through unchanged.
  * Unknown single-segment, extension-less URIs now return a 404 with a short cache header.

* **Bug Fixes**
  * Improved request validation and error handling to reduce routing failures and preserve normal index/origin behavior.

### CODE REVIEW

**Review by Kravalg — CHANGES_REQUESTED** [review]
The current solution is over engineering
It can be much easier

For example:

```

/**
 * ES5.1 compatible (no let/const/arrow functions).
 */
'use strict';

var ROUTE_MAP = Object.freeze({
  '/': '/index.html',
  '/about': '/about/index.html',
  '/about/': '/about/index.html',
  '/en': '/en/index.html',
  '/en/': '/en/index.html',
  '/swagger': '/swagger.html'
});

/**
 * 1) Single source of truth: allowed paths are simply the keys of ROUTE_MAP.
 * 2) We use the array to check existence; the map to resolve the target file.
 */
var ALLOWED_PATHS = Object.freeze(Object.keys(ROUTE_MAP));

function handler(event) {
  var request = event.request;

  if (!request || typeof request.uri !== 'string') {
    var host = (request && request.headers && request.headers.host && request.headers.host.value) || '';
    console.log('cloudfront_routing: missing/invalid request.uri', 'host=', host, 'uri=', request && request.uri);
    return request;
  }

  try {
    var uri = request.uri;

    // Fast-path: explicitly allowed -> rewrite via ROUTE_MAP.
    if (Object.prototype.hasOwnProperty.call(ROUTE_MAP, uri)) {
      request.uri = ROUTE_MAP[uri];
      return request;
    }

    // Optional: allow static assets (anything with an extension) to pass through.
    // Remove this block if you want strict allowlist-only behavior.
    var lastSlash = uri.lastIndexOf('/');
    var lastSegment = uri.substring(lastSlash + 1);
    if (lastSegment.indexOf('.') !== -1) {
      return request;
    }

    // Not in allowlist -> 404.
    if (ALLOWED_PATHS.indexOf(uri) === -1) {
      return {
        statusCode: 404,
        statusDescription: 'Not Found',
        headers: { 'cache-control': { value: 'public, max-age=60' } }
      };
    }

    // (Shouldn’t get here; kept as a safe default.)
    return request;
  } catch (err) {
    console.log('cloudfront_routing: error', err);
    return request;
  }
}

```

File: scripts/cloudfront_routing.js [hunk 1]
```diff
@@ -1,48 +1,72 @@
...
         }
 
-        else if (lastSegment.indexOf('.') === -1 && segments.length > 2) {
-            request.uri = uri + '/index.html';
+        // Narrow guard: only 404 unknown single-segment, extension-less paths.
+        // Multi-segment paths (e.g., /en/docs) fall back to origin so S3 can decide.
+        var parts = uri.split('/');
+        var i = 0;
+        var segmentCount = 0;
+        for (i = 0; i < parts.length; i++) {
```
Comment (Kravalg) [inline scripts/cloudfront_routing.js]: Please refactor this code with i = o

**Review by Kravalg — CHANGES_REQUESTED** [review]

**Comment by bra1n2h** [comment]
This approach also works, i tried different requests and got 404 error

**Review by Kravalg — APPROVED** [review]
Good job 💪
