### PR TITLE
fix(#203): move CI pipeline control from infrastructure to website rep…

### LINKED ISSUE #203: CI Pipeline Control Moved from Infrastructure to Website Repository
**Describe the bug**
CI pipeline logic was scattered across the infrastructure repository in complex bash scripts, making it difficult for developers to control and test their own CI pipeline locally

**To Reproduce**
1. Steps to reproduce the behavior:
2. Go to website-infrastructure/aws/scripts/sh/
3. See 800+ lines of bash scripts managing website CI
4. Check website-infrastructure/aws/buildspecs/website/batches/
5. See buildspecs calling multiple infrastructure scripts

**Expected behavior**
Developers should own and control their CI pipeline with all necessary files in the website repository.

### PR DESCRIPTION
**Pull request by bra1n2h**
## Description
This PR transfers CI pipeline ownership from the infrastructure team to the development team by moving all CI-related files and logic from website-infrastructure to the website repository. The change simplifies buildspecs from ~80 lines to ~25 lines each and enables developers to test CI commands locally.

## Related Issue
Fixes #203 

## Motivation and Context
Problem:
- CI pipeline was controlled by infrastructure team with complex bash scripts
- Developers couldn't replicate CI environment locally
- 800+ lines of scripts made debugging difficult
- Split responsibility between infrastructure and development teams

Solution:
- Transfer full CI control to developers
- Use CodeBuild's native Docker support
- Simplify architecture while maintaining all functionality

## How Has This Been Tested?
- Network setup tested: make setup-dind-network creates external network
- Container connectivity verified: Services can communicate via network
- Buildspec syntax validated: All 9 buildspecs use correct YAML structure
- Makefile targets confirmed: All test commands work with simplified logic
- Backwards compatibility: Container names preserved for existing scripts

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] I have performed a self-review of my code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING.md**](https://github.com/VilnaCRM-Org/frontend-ssr-template/blob/main/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] New components have been added to Storybook.
- [ ] You have only one commit (if not, squash them into one commit).

## Summary by CodeRabbit

* **Style**
  * Adjusted Vilna CRM Email icon styling for improved alignment (switched to inline style).

* **New Features**
  * Added environment defaults, PNPM-backed node check, curl-based health checks, CI-safe Chromium wrapper, and many new public Makefile targets for visual, E2E, load, Lighthouse, and Chromium flows.

* **Tests**
  * Added containerized CI orchestration scripts covering unit, mutation, lint, visual, E2E, load, and memory-leak testing with artifact collection and reporting.

* **Chores**
  * Standardized container names across compose files, set prod shared-memory sizing, updated API URLs, and made prod startup wait on health checks.

### CODE REVIEW

File: scripts/ci/setup_makefile_targets.sh [hunk 1]
```diff
@@ -0,0 +1,95 @@
...
+			exit 1; \
+		fi; \
+	done
+start-dind: ## Start application in DinD mode with network setup
+	@echo "🐳 Starting application in true DinD mode..."
+	make setup-dind-network
+	$(DOCKER_COMPOSE) $(DOCKER_COMPOSE_DEV_FILE) up -d dev
+	make wait-for-dev-dind
+MAKEFILE_PART1
+
```
[the remark this answers is not in the document]
Comment (bra1n2h) [reply scripts/ci/setup_makefile_targets.sh]: let's keep it in the script instead of another Makefile

File: scripts/ci/batch_unit_mutation_lint_targets.sh [hunk 2]
```diff
@@ -0,0 +1,218 @@
...
+		exit 1; \
+	fi
+	@echo "🧹 Cleaning up temporary container..."
+	@docker rm -f website-dev-temp
+	@echo "🎉 All unit tests completed successfully in true DinD mode!"
+	@echo "📊 Summary: Both client and server tests passed in containerized environment"
+else
+	@echo "🐳 Running unit tests with standard Docker Compose"
+	$(UNIT_TESTS) TEST_ENV=client $(JEST_BIN) $(JEST_FLAGS)
+	$(UNIT_TESTS) TEST_ENV=server $(JEST_BIN) $(JEST_FLAGS) $(TEST_DIR_APOLLO)
```
[the remark this answers is not in the document]
Comment (bra1n2h) [reply scripts/ci/batch_unit_mutation_lint_targets.sh]: You were absolutely right to check this - undefined Makefile variables are a common source of "command not found" errors. But in this case, the repository maintainers have properly defined the UNIT_TESTS variable with different behaviors for CI vs local development environments.
The script is working as intended! 🎉

File: scripts/ci/batch_unit_mutation_lint_targets.sh [hunk 3]
```diff
@@ -0,0 +1,278 @@
...
+	@echo "🛠️ Starting container in background for file operations..."
+	docker run -d --name website-dev-temp --network website-network website-dev tail -f /dev/null
+	@echo "📂 Copying source files into container..."
+	@if docker cp . website-dev-temp:/app/; then \
+		echo "✅ Source files copied successfully"; \
+	else \
+		echo "❌ Failed to copy source files"; \
+		docker rm -f website-dev-temp; \
+		exit 1; \
+	fi
```
[the remark this answers is not in the document]
Comment (bra1n2h) [reply scripts/ci/batch_unit_mutation_lint_targets.sh]: files that we copy we need to run tests and saving the artifacts for ex. That's why we copy all the files. ALso we have ignore files

**Review by Kravalg — CHANGES_REQUESTED** [review]
Why do we need to add commands dynamically to the Makefile ?

**Review by Kravalg — CHANGES_REQUESTED** [review]
All CI checks should be green
The next thing is duplicating logic of what makefile does
The main idea is to have one makefile for local, github and aws CI
Please rewrite your scripts to use make commands instead of use plain docker and docker compose commands

**Comment by bra1n2h** [comment]
Our CI scripts use a hybrid approach - Makefile commands for simple tests (unit, lint, mutation) and custom Docker logic for complex orchestrated tests (E2E, visual, load, memory leak, Lighthouse). DIND requires manual container management with explicit naming and networking. Complex tests like E2E, visual, and load tests require multi-container coordination with specific networking and file sharing between containers, which the Makefile's docker-compose commands can't handle properly in the DIND nested environment. Simple tests (unit, lint, mutation) work fine with Makefile because they run in a single container without requiring complex Docker orchestration or inter-service communication.

File: scripts/ci/batch_lhci_leak.sh [hunk 4]
```diff
@@ -0,0 +1,575 @@
...
+    if [ -f "$file" ]; then
+        if grep -q "$old_ref" "$file"; then
+            sed -i "s|$old_ref|$new_ref|g" "$file"
+            echo "✅ Updated references from $old_ref to $new_ref in $file"
+        fi
+    fi
+}
+
+# Configure Docker Compose files for DIND
+configure_docker_compose() {
```
Comment (Kravalg) [inline scripts/ci/batch_lhci_leak.sh]: This function is not needed
Please change the .yaml files of you need to add the container_name

File: scripts/ci/batch_lhci_leak.sh [hunk 5]
```diff
@@ -0,0 +1,575 @@
...
+            echo "✅ Added container_name: ${container_name} to ${service} in ${file}"
+        else
+            echo "ℹ️  Container name already exists for ${service} in ${file}"
+        fi
+    else
+        echo "⚠️  File ${file} not found, skipping..."
+    fi
+}
+
+# Function to update environment variable references from service names to container names
```
Comment (Kravalg) [inline scripts/ci/batch_lhci_leak.sh]: Please remove all comments, your code should be self explainable

File: scripts/ci/batch_lhci_leak.sh [hunk 6]
```diff
@@ -0,0 +1,575 @@
...
+        if [ "$i" -eq 30 ]; then
+            echo "❌ Container failed to start within 60 seconds"
+            docker ps -a --filter "name=$PROD_CONTAINER_NAME"
+            exit 1
+        fi
+    done
+    
+    echo "🔍 Testing $PROD_CONTAINER_NAME service connectivity on port $NEXT_PUBLIC_PROD_PORT..."
+    for i in $(seq 1 60); do
+        if docker exec "$PROD_CONTAINER_NAME" sh -c "curl -f http://localhost:$NEXT_PUBLIC_PROD_PORT >/dev/null 2>&1"; then
```
Comment (Kravalg) [inline scripts/ci/batch_lhci_leak.sh]: Why do we need this code ?
The docker compose has healthchecks for this functionality

File: scripts/ci/batch_lhci_leak.sh [hunk 7]
```diff
@@ -0,0 +1,575 @@
...
+            echo "✅ Service is responding on port $NEXT_PUBLIC_PROD_PORT!"
+            break
+        fi
+        echo "Attempt $i: Service not ready, checking container status..."
+        if [ "$((i % 10))" -eq 0 ]; then
+            echo "Debug info at attempt $i:"
+            docker exec "$PROD_CONTAINER_NAME" ps aux 2>/dev/null || echo "Cannot access container processes"
+            docker exec "$PROD_CONTAINER_NAME" netstat -tulpn 2>/dev/null | grep ":$NEXT_PUBLIC_PROD_PORT" || echo "Port $NEXT_PUBLIC_PROD_PORT not bound"
+        fi
+        sleep 3
```
Comment (Kravalg) [inline scripts/ci/batch_lhci_leak.sh]: Please remove sleep from all scripts since that is the bad practice

File: scripts/ci/batch_lhci_leak.sh [hunk 8]
```diff
@@ -0,0 +1,575 @@
...
+        if [ "$i" -eq 60 ]; then
```
Comment (Kravalg) [inline scripts/ci/batch_lhci_leak.sh]: I don't understand why do we need this code at all ?
Docker compose can check health of the services and you can use depends on instead of all of this code

File: scripts/ci/batch_lhci_leak.sh [hunk 9]
```diff
@@ -0,0 +1,575 @@
...
+}
+
+# Start production environment in DIND mode
+start_prod_dind() {
+    echo "🐳 Starting production environment in true Docker-in-Docker mode"
+    echo "Setting up Docker network..."
+    setup_docker_network
+    configure_docker_compose
+    echo "Building production container image..."
+    docker compose -f "$COMMON_HEALTHCHECKS_FILE" -f "$DOCKER_COMPOSE_TEST_FILE" build
```
Comment (Kravalg) [inline scripts/ci/batch_lhci_leak.sh]: Please use make commands instead of using docker compose directly here

**Review by Kravalg — CHANGES_REQUESTED** [review]
It will be better to refactor all of the bash scripts, because you need to use as much as possible the make commands instead of using docker compose and docker execute everywhere

File: scripts/ci/batch_lhci_leak.sh (hunk 4 above)
Comment (bra1n2h) [reply scripts/ci/batch_lhci_leak.sh]: done

File: scripts/ci/batch_lhci_leak.sh (hunk 5 above)
Comment (bra1n2h) [reply scripts/ci/batch_lhci_leak.sh]: done

File: scripts/ci/batch_lhci_leak.sh (hunk 6 above)
Comment (bra1n2h) [reply scripts/ci/batch_lhci_leak.sh]: Removed this code is not needed

File: scripts/ci/batch_lhci_leak.sh (hunk 7 above)
Comment (bra1n2h) [reply scripts/ci/batch_lhci_leak.sh]: done

File: scripts/ci/batch_lhci_leak.sh (hunk 8 above)
Comment (bra1n2h) [reply scripts/ci/batch_lhci_leak.sh]: removed

File: scripts/ci/batch_lhci_leak.sh (hunk 9 above)
Comment (bra1n2h) [reply scripts/ci/batch_lhci_leak.sh]: done

**Review by Kravalg — CHANGES_REQUESTED** [review]
We should use only make commands to run the CI checks 
There are too much unnecessary code that will be complicated to maintain

File: src/features/swagger/components/Header/Drawer/VilnaCRMEmail/styles.ts
Comment (Kravalg) [inline src/features/swagger/components/Header/Drawer/VilnaCRMEmail/styles.ts:1]: Why you added the frontend code ?
Please remove it

File: src/features/swagger/components/Header/Drawer/VilnaCRMEmail/VilnaCRMEmail.tsx [hunk 10]
```diff
@@ -0,0 +1,27 @@
+import { Stack } from '@mui/material';
```
Comment (Kravalg) [inline src/features/swagger/components/Header/Drawer/VilnaCRMEmail/VilnaCRMEmail.tsx:1]: Why you added the frontend code ?
Please remove it

File: Makefile [hunk 11]
```diff
@@ -115,9 +115,103 @@ start: ## Start the application
 
 wait-for-dev: ## Wait for the dev service to be ready on port $(DEV_PORT).
 	@echo "Waiting for dev service to be ready on port $(DEV_PORT)..."
-	@while ! npx wait-on http://$(WEBSITE_DOMAIN):$(DEV_PORT) 2>/dev/null; do printf "."; done
+	@while ! curl -s -f http://$(WEBSITE_DOMAIN):$(DEV_PORT) >/dev/null 2>&1; do printf "."; sleep 1; done
 	@printf '\nDev service is up and running!\n'
 
+create-temp-dev-container-dind: ## Create a temporary dev container for DIND testing (TEMP_CONTAINER_NAME required)
+	@if [ -z "$(TEMP_CONTAINER_NAME)" ]; then \
```
Comment (Kravalg) [inline Makefile]: Please follow the DRY principle in Makefile and refactor this file to do not repeat the same blocks of code between commands

File: scripts/ci/batch_lhci_leak.sh [hunk 12]
```diff
@@ -0,0 +1,141 @@
...
+PROD_CONTAINER_NAME=${PROD_CONTAINER_NAME:-"website-prod"}
+DOCKER_COMPOSE_DEV_FILE=${DOCKER_COMPOSE_DEV_FILE:-"docker-compose.yml"}
+DOCKER_COMPOSE_TEST_FILE=${DOCKER_COMPOSE_TEST_FILE:-"docker-compose.test.yml"}
+COMMON_HEALTHCHECKS_FILE=${COMMON_HEALTHCHECKS_FILE:-"common-healthchecks.yml"}
+echo "🐳 DIND Environment Setup Script"
+echo "================================"
+setup_docker_network() {
+    echo "📡 Setting up Docker network..."
+    docker network create "$NETWORK_NAME" 2>/dev/null || echo "Network $NETWORK_NAME already exists"
+    echo "✅ Docker network configured"
```
Comment (Kravalg) [inline scripts/ci/batch_lhci_leak.sh]: Please remove echo after each command inside all bash scripts in scripts/ci directories 
That is hard to read and maintain

**Review by Kravalg — CHANGES_REQUESTED** [review]

File: src/features/swagger/components/Header/Drawer/VilnaCRMEmail/VilnaCRMEmail.tsx (hunk 10 above)
Comment (bra1n2h) [reply src/features/swagger/components/Header/Drawer/VilnaCRMEmail/VilnaCRMEmail.tsx:1]: I tested docker tests and got error during Typescript check, I implemented this change under Yuliia's review and Typescript check passed after this change, should I remove it anyway?

File: src/features/swagger/components/Header/Drawer/VilnaCRMEmail/styles.ts
Comment (bra1n2h) [reply src/features/swagger/components/Header/Drawer/VilnaCRMEmail/styles.ts:1]: I tested docker tests and got error during Typescript check, I implemented this change under Yuliia's review and Typescript check passed after this change, should I remove it anyway?

File: Makefile [hunk 13]
```diff
@@ -221,6 +339,17 @@ wait-for-prod-health: ## Wait for the prod container to reach a healthy state.
...
 	done
 
+.PHONY: visual-direct e2e-direct all clean
+visual-direct: start-prod ## Start production and run visual tests directly (no shell wrapper)
+	$(playwright-test) $(TEST_DIR_VISUAL)
+
+e2e-direct: start-prod ## Start production and run E2E tests directly (no shell wrapper)
+	$(playwright-test) $(TEST_DIR_E2E)
+
+all: build ## Default aggregate target to build the project
```
Comment (Kravalg) [inline Makefile:349]: Please remove „all” and „clean” make commands

**Review by Kravalg — CHANGES_REQUESTED** [review]

**Review by Kravalg — APPROVED** [review]
